# name: CI

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.12.4

#       - name: Install dependencies
#         run: pip install -r api/requirements.txt

#       - name: Run CI
#         run: make CI
